#!/bin/bash
currentSink=$(pacmd stat | grep "Default sink name" | cut -d" " -f4 2>&1)

icon="/home/david/.config/dunst/volume.png"
if [ "$currentSink" == "alsa_output.usb-Corsair_Corsair_VOID_PRO_Wireless_Gaming_Headset-00.analog-stereo" ]; then
  icon="/home/david/.config/dunst/headphones.png"
fi

function send_notification() {
  volume=$(pactl get-sink-volume $currentSink | grep Volume | cut -d"/" -f2 | tr -dc '0-9' 2>&1)
	dunstify -a "changevolume" -u low -r "9993" -h int:value:"$volume" -I "$icon" "General volume: ${volume}%" -t 2000
}

case $1 in
up)
  pactl set-sink-mute @DEFAULT_SINK@ 0
  pactl set-source-mute @DEFAULT_SOURCE@ 0
  pactl set-sink-volume @DEFAULT_SINK@ +2%
	send_notification
	;;
down)
	pactl set-sink-mute @DEFAULT_SINK@ 0
  pactl set-source-mute @DEFAULT_SOURCE@ 0
  pactl set-sink-volume @DEFAULT_SINK@ -2%
  send_notification
	;;
notify)
  pactl set-sink-mute @DEFAULT_SINK@ 0
  pactl set-source-mute @DEFAULT_SOURCE@ 0
  send_notification
  ;;
mute)
  pactl set-sink-mute @DEFAULT_SINK@ toggle
  pactl set-source-mute @DEFAULT_SOURCE@ toggle

  mute=$(pactl get-sink-mute $currentSink | cut -d" " -f2 2>&1)

  if [ "$mute" == "no" ]; then
    send_notification
  else
		dunstify -i volume-mute -a "changevolume" -I /home/david/.config/dunst/mute.png -t 2000000000 -r 9993 -u low "Muted"
  fi
	;;
esac
