#!/bin/env bash
set -e

volume=$(pactl list sink-inputs | grep -B 13 "Spotify" | grep Volume | cut -d"/" -f2 | tr -dc '0-9' 2>&1)
emoji=""

if [ "$volume" != "" ]; then
  printf "$emoji $volume%%"
fi
