#!/bin/env bash
set -e

currentSink=$(pacmd stat | grep "Default sink name" | cut -d" " -f4 2>&1)
mute=$(pactl get-sink-mute $currentSink | cut -d" " -f2 2>&1)

emoji=""
if [ "$currentSink" == "alsa_output.pci-0000_01_00.1.hdmi-stereo" ]; then
    emoji=''
fi

if [ "$mute" == "no" ]; then
    printf "$emoji"
else
    printf ""
fi
