#!/bin/sh
discord &
nextcloud &
steam-runtime -silent &
flameshot &
redshift-gtk &
xscreensaver -no-splash &
$HOME/.config/scripts/screenSaver &
sleep 5; env SPOTIFYD_CLIENT_ID=d6ba59f07e1c4f44947b0832c748b9e3 spotifyd
