#!/bin/env bash
set -e

volume=$(pactl list sink-inputs | grep -B 22 -e 'process.binary = "Discord"' | grep -B 18 -e 'application.name = "WEBRTC VoiceEngine"' | grep Volume | cut -d"/" -f2 | tr -dc '0-9' 2>&1)

if [ "$volume" != "" ]; then
  printf "$volume%%"
fi
