#!/bin/env bash
set -e

currentSink=$(pactl info | grep "Default Sink" | cut -d" " -f3 2>&1)
mute=$(pactl get-sink-mute $currentSink | cut -d" " -f2 2>&1)

if [ "$mute" == "no" ]; then

    if [[ $currentSink != *"Corsair"* ]]; then
        printf ''
    else
        printf ""
    fi

else
    printf ""
fi
