#!/bin/bash
currentSink=$(pactl info | grep "Default Sink" | cut -d" " -f3 2>&1)

if [[ "$currentSink" == *"Corsair"* ]]; then
  pactl set-default-sink alsa_output.pci-0000_2b_00.1.hdmi-stereo
else
  pactl set-default-sink alsa_output.usb-Corsair_Corsair_VOID_PRO_Wireless_Gaming_Headset-00.analog-stereo
fi

$HOME/.config/scripts/wm/changevolume notify
